# Generated by Django 5.2.9 on 2025-12-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='truth_score',
            field=models.IntegerField(default=0),
        ),
    ]
